#!/usr/bin/env python3
"""Prepare the photos shown on checkpoint screens.

  # add or replace a photo in slot 1, cropped around x=350,y=340, 470px square
  python3 tools/make_checkpoints.py 1 path/to/photo.jpg --crop 350,340,470

  # rebuild src/checkpoints-data.js from whatever is already in assets/checkpoints
  python3 tools/make_checkpoints.py

Photos are stored as ordinary JPEGs (they are shown as photos, not pixel art)
and inlined as base64 so the page also works straight from file://.
"""
import argparse
import base64
import glob
import os
import re

from PIL import Image, ImageOps

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PHOTO_DIR = os.path.join(ROOT, "assets", "checkpoints")
OUT = os.path.join(ROOT, "src", "checkpoints-data.js")
SIZE = 400          # square, big enough to stay sharp on a zoomed canvas
QUALITY = 82


def build_photo(source, slot, crop):
    img = ImageOps.exif_transpose(Image.open(source)).convert("RGB")
    if crop:
        cx, cy, side = crop
    else:
        side = min(img.size)
        cx, cy = img.width // 2, img.height // 2
    half = side // 2
    box = (cx - half, cy - half, cx + half, cy + half)
    img = img.crop(box).resize((SIZE, SIZE), Image.LANCZOS)
    os.makedirs(PHOTO_DIR, exist_ok=True)
    path = os.path.join(PHOTO_DIR, "%s.jpg" % slot)
    img.save(path, "JPEG", quality=QUALITY, optimize=True, progressive=False)
    print("wrote %s (%d KB)" % (path, os.path.getsize(path) // 1024))


def write_data():
    photos = sorted(glob.glob(os.path.join(PHOTO_DIR, "*.jpg")),
                    key=lambda p: int(re.sub(r"\D", "", os.path.basename(p)) or 0))
    with open(OUT, "w") as fh:
        fh.write("// Generated by tools/make_checkpoints.py - do not edit by hand.\n")
        fh.write("const CHECKPOINT_IMAGES = {\n")
        for path in photos:
            slot = os.path.splitext(os.path.basename(path))[0]
            data = base64.b64encode(open(path, "rb").read()).decode()
            fh.write('  "%s": "data:image/jpeg;base64,%s",\n' % (slot, data))
        fh.write("};\n")
    total = sum(os.path.getsize(p) for p in photos)
    print("wrote %s (%d photos, %d KB of image data)" % (OUT, len(photos), total // 1024))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("slot", nargs="?", help="checkpoint slot number, e.g. 1")
    ap.add_argument("photo", nargs="?", help="source image")
    ap.add_argument("--crop", help="centre and side of the square crop: cx,cy,side")
    args = ap.parse_args()

    if args.slot and args.photo:
        crop = tuple(int(v) for v in args.crop.split(",")) if args.crop else None
        build_photo(args.photo, args.slot, crop)
    write_data()


if __name__ == "__main__":
    main()
