#!/usr/bin/env python3
"""Prepare the photos of the Лёши shown on checkpoint screens.

Every Лёша lives in a slot. A slot holds one photo, or several frames that are
played as a loop (the walking one):

  python3 tools/make_checkpoints.py 1 makeup.jpg --crop 350,340,470
  python3 tools/make_checkpoints.py 4 walk1.jpg walk2.jpg walk3.jpg

  python3 tools/make_checkpoints.py          # only rebuild src/checkpoints-data.js

Frames are stored as ordinary JPEGs under assets/checkpoints/<slot>/ - they are
shown as photos, not pixel art - and inlined as base64 so the page also works
straight from file://.
"""
import argparse
import base64
import glob
import os
import shutil

from PIL import Image, ImageOps

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PHOTO_DIR = os.path.join(ROOT, "assets", "checkpoints")
OUT = os.path.join(ROOT, "src", "checkpoints-data.js")


def build_slot(slot, sources, crop, size, quality):
    # animations carry several frames, so they get a smaller, lighter frame size
    if size is None:
        size = 400 if len(sources) < 3 else 340
    if quality is None:
        quality = 82 if len(sources) < 3 else 76

    slot_dir = os.path.join(PHOTO_DIR, str(slot))
    if os.path.isdir(slot_dir):
        shutil.rmtree(slot_dir)
    os.makedirs(slot_dir)

    for i, source in enumerate(sources, start=1):
        img = ImageOps.exif_transpose(Image.open(source)).convert("RGB")
        if crop:
            cx, cy, side = crop
        else:
            side = min(img.size)
            cx, cy = img.width // 2, img.height // 2
        half = side // 2
        img = img.crop((cx - half, cy - half, cx + half, cy + half))
        img = img.resize((size, size), Image.LANCZOS)
        img.save(os.path.join(slot_dir, "%02d.jpg" % i), "JPEG",
                 quality=quality, optimize=True)
    print("slot %s: %d frame(s) at %dpx" % (slot, len(sources), size))


def write_data():
    slots = sorted(
        (d for d in os.listdir(PHOTO_DIR) if os.path.isdir(os.path.join(PHOTO_DIR, d))),
        key=lambda d: int("".join(c for c in d if c.isdigit()) or 0))
    total = 0
    with open(OUT, "w") as fh:
        fh.write("// Generated by tools/make_checkpoints.py - do not edit by hand.\n")
        fh.write("// Each slot holds one or more frames; several frames play as a loop.\n")
        fh.write("const CHECKPOINT_IMAGES = {\n")
        for slot in slots:
            frames = sorted(glob.glob(os.path.join(PHOTO_DIR, slot, "*.jpg")))
            fh.write('  "%s": [\n' % slot)
            for frame in frames:
                total += os.path.getsize(frame)
                data = base64.b64encode(open(frame, "rb").read()).decode()
                fh.write('    "data:image/jpeg;base64,%s",\n' % data)
            fh.write("  ],\n")
        fh.write("};\n")
    print("wrote %s (%d Лёш, %d KB of image data)" % (OUT, len(slots), total // 1024))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("slot", nargs="?", help="slot number, e.g. 1")
    ap.add_argument("photos", nargs="*", help="source image(s); several make a loop")
    ap.add_argument("--crop", help="centre and side of the square crop: cx,cy,side")
    ap.add_argument("--size", type=int, help="frame size in pixels")
    ap.add_argument("--quality", type=int, help="JPEG quality")
    args = ap.parse_args()

    if args.slot and args.photos:
        crop = tuple(int(v) for v in args.crop.split(",")) if args.crop else None
        build_slot(args.slot, args.photos, crop, args.size, args.quality)
    write_data()


if __name__ == "__main__":
    main()
