// Generated by tools/make_assets.py - do not edit by hand.
const HERO_PNG = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAEl0lEQVR42sVXX0xbVRz+DrvdcGVpoA1cGQ2FsglhxtUxarUPmEUHAxfmkySyF181xGhYiC/1BaMYTUTe8GWYIE8sbMDUGH0wskE3WZSwAS1twHJL6BYiF1CuOz605/S095bdbg/7JTe595xzz/f9/n3nXvLBFMXTtAI8ZXtiApKU37hu3eMCMBtqcety2DkZImZJSGaZ5gItLq3JOd85GSIHD6TH//0vjwiIL4obDLW4aUdLO67f+hMAcH8lpFtX4qzJIPLOD8mIHDygJ0EuzVBT4N+8ntxM9NgIXE/GjQfrS+i4GiKHD+kdIpdmqCFgNrjodT52fyUEcoiiuLSGnP18CFa5NDMFTwqeKwolTjfEOnmwvkS//7BTR8JUG4rgbUeP8MsnqRlARsSy58nwp+bbUPTeJ6lo9J7mc6HICuxlMtoA4OjJfR1IxBVMpaJw/RbIm/noAPPaW58E39vaAgC8WFmx7zubhMBhtSYf6mvRqKoIjC4BAFRlnafBFAFNrgQtd4HEIo9caykqAgA4Us+03AUAsAMAxtB86gRovlL88vN1pqt+b2uLXwAMSdO70+YIvHV5igxPXnnsc8KIxEPPqwAA2bIN2bKdJiBbtnUbfHfRR/u7ewxDnH1vloRfU3J3gWzZhrJ32HSe2eas6ADARqlpcgAgbf1yDQCwZGLxhqri3m4BJCWqm3O7nACA29HVjOJ9rvBhsihZR5g5jEZ6u3QHxG9/zGPzzgymNKtO/VqrZH5/7a+/hflZLkbNp048+oOkoVrCSG8X7WhpR6fHk1avWIR77ZNUtFbJXOEYOItANjm2bvPOTeMINFQbS4Hb5UT/a8089KJlR8FeJsNGaZLEjVnjs0KIkl9TkPjqI8zXnYEUDGvce9FslILEIlxI3C4n3C4n7u0WoE2JIiHJusJ0pCIyvqygtUrGlGaFT1L10rw4h+mbMzhSdwYFDdVSBnjf4AAZnryC29FVbKgqdo9XwGG18upmRWUvk/klynKj9zQuvnSSp4uNTcTW8GX7G0SMWsHvP+eW4kRcgbe+FnRhFbTcBUssAkeq9bLPAbHlHFYrbJUVQGpNtm7Q1EEGAK/Yn9ErYTCsoW9wgEzE1jJyz1Jh1N9sLvuerX3322H0d/cQcS4RV7DT5NdHIFdRisom9rq3vhaIRdJkF+dgA/DjdFCXHpZ/loJgWAN5/4urOtBgWEPd/E8IjI5xKSYpkFBkBYm4AnuZDLfLmfGciCsYX1Z4DSTiCiZiawhcOE+YEG2oKmyUwlJUhJ0mf5LAfjbS20X7u3uQWJzjYMwDJjys2Fh7ljjd8EkqJmJrOFf+LGHrmVYAgLX1bFqIsjtBHOsbHCDvffaJTgfEjxVmTKQYeHFpDRlfzjx87MfqOTgnIGoBIxIMa3z867c7SGB0jHvgk1RcvjGLRFyBJlfC9oKXRwQAJmJroP8QYvTBunu8AiKmYcUZFWLgwnkSGB1L/vF4PPg49X0YikQzgFPzRKwLMfyFC6ucBIB0DYigwbCGhmqJs/RrCq9eAGBEdP+EHg8RpZz1u9gxO01+FC6s4teUkv4PuNkKoyPgwHUAAAAASUVORK5CYII=";

const SPRITE_DATA = {
  "katy": {
    "w": 18,
    "pal": {
      "K": "#1b0f24",
      "k": "#3c2350",
      "S": "#f6c49d",
      "s": "#d09a72",
      "W": "#ffffff",
      "B": "#39a9ea",
      "L": "#e0284c",
      "p": "#ef9aa4",
      "D": "#a34bd8",
      "d": "#7a30a8",
      "M": "#ffd447"
    },
    "rows": [
      "......KKKKKK......",
      "....KKKKKKKKKK....",
      "...KKKKKKKKKKKK...",
      "..KKKKKKKKKKKKKK..",
      "..KKKkkkkkkkkKKK..",
      "..KKSSSSSSSSSSKK..",
      "..KKSSSSSSSSSSKK..",
      "..KKSWBSSSSWBSKK..",
      "..KKSsSSSSSSsSKK..",
      "..KKpSSSSSSSSpKK..",
      "..KKSSsLLLLsSSKK..",
      "..KKSSSSSSSSSSKK..",
      "..KKKSSSSSSSSKKK..",
      "...KKKSSSSSSKKK...",
      "...KKKKSSSSKKKK...",
      "..KKKDDDDDDDDKKK..",
      "..KKDDDDDDDDDDKK..",
      "..KKDDDDMMDDDDKK..",
      ".KKKDDDDDDDDDDKKK.",
      ".KKDDDDDDDDDDDDKK.",
      "SKKDDDDDDDDDDDDKKS",
      "SSKDDDDddddDDDDKSS",
      ".S.DDDDDDDDDDDD.S.",
      "...DDDDDDDDDDDD...",
      "....SSS....SSS....",
      "....ss......ss...."
    ]
  },
  "colaCap": {
    "w": 28,
    "pal": {
      "R": "#e2243a",
      "r": "#a8122a",
      "H": "#ff6070",
      "W": "#ffffff",
      "D": "#4a0d1b",
      "M": "#e6e8f0",
      "m": "#8d94a8",
      "f": "#c41b31"
    },
    "rows": [
      "..........DmMMMmmD..........",
      "..........DmMMMmmD..........",
      "..........DmMMMmmD..........",
      "..........DmMMMmmD..........",
      ".........DmMMMMMmmD.........",
      "..........DrHRRrrD..........",
      "..........DrHRRrrD..........",
      "..........DrHRRrrD..........",
      "..........DrHRRrrD..........",
      "..........DrHRRrrD..........",
      "..........DrHRRrrD..........",
      "..........DrHRRrrD..........",
      "..........DrHRRrrD..........",
      "..........DrHRRrrD..........",
      "..........DrHRRrrD..........",
      "........DrHRRRRRRrrD........",
      ".......DrHRRRRRRRRrrD.......",
      ".....DrHRRRRRRRRRRRRrrD.....",
      "....DrHRRRRRRRRRRRRRRrrD....",
      "..DrHRRRRRRRRRRRRRRRRRRrrD..",
      ".DrHRRRRRRRRRRRRRRRRRRRRrrD.",
      ".DrHRRRRRRRRRRRRRRRRRRRRrrD.",
      ".DrHRRRRRRRRRRRRRRRRRRRRrrD.",
      ".DrHRRRRRRRRRRRRRRRRRRRRrrD.",
      "DrHRRRRRRRRRRRRRRRRRRRRRRrrD",
      "DrHRRRRRRRRRRRRRRRRRRRRRRrrD",
      "DrWWWWWWWWWWRRRRRRWWWWWWRrrD",
      "DrWWWWWWWWWWWWWRRRRRWWWWWrrD",
      "DrHRRRWWWWWWWWWWWWWWRRRRRrrD",
      "DrHWWWWWWWWWWWRRRRRRRRRRRrrD",
      "DrHRRRRRRRRRRRRRRRRRRRRRRrrD",
      "DrHRRRRRRRRRRRRRRRRRRRRRRrrD",
      ".DrHRRRRRRRRRRRRRRRRRRRRrrD.",
      ".DrHRfRRRfRRRfRRRfRRRfRRrrD.",
      "DrHRfRRRfRRRfRRRfRRRfRRRfrrD",
      "DrHRfRRRfRRRfRRRfRRRfRRRfrrD"
    ]
  },
  "colaBody": {
    "w": 28,
    "pal": {
      "R": "#e2243a",
      "r": "#a8122a",
      "H": "#ff6070",
      "W": "#ffffff",
      "D": "#4a0d1b",
      "M": "#e6e8f0",
      "m": "#8d94a8",
      "f": "#c41b31"
    },
    "rows": [
      "DrHRfRRRfRRRfRRRfRRRfRRRfrrD",
      "DrHRfRRRfRRRfRRRfRRRfRRRfrrD",
      "DrHRfRRRfRRRfRRRfRRRfRRRfrrD",
      "DrHRfRRRfRRRfRRRfRRRfRRRfrrD"
    ]
  },
  "gullUp": {
    "w": 15,
    "pal": {
      "W": "#ffffff",
      "G": "#b9c4d4",
      "g": "#8b97ab",
      "O": "#ff9b22",
      "K": "#241533"
    },
    "rows": [
      ".........KK....",
      "........KGG....",
      ".......GGGG....",
      "......GGGG.....",
      ".....GGGG......",
      "OOWWWWWWW......",
      ".WWKWWWWWWW....",
      ".WWWWWWWWWWWG..",
      "..WWWWWWWWGG...",
      "...WWWWWg......",
      ".....gg........"
    ]
  },
  "gullDown": {
    "w": 15,
    "pal": {
      "W": "#ffffff",
      "G": "#b9c4d4",
      "g": "#8b97ab",
      "O": "#ff9b22",
      "K": "#241533"
    },
    "rows": [
      "...............",
      "...............",
      "OOWWWWWWW......",
      ".WWKWWWWWWW....",
      ".WWWWWWWWWWWG..",
      "..WWWWWWWWGG...",
      "...GGGGg.......",
      "....GGGG.......",
      ".....GGGG......",
      "......GGG......",
      ".......KK......"
    ]
  },
  "droneA": {
    "w": 16,
    "pal": {
      "K": "#2b2438",
      "k": "#4a4160",
      "M": "#c8ccd8",
      "W": "#ffffff",
      "B": "#39a9ea",
      "R": "#ff4d4d",
      "g": "#7c8496"
    },
    "rows": [
      "..ggg......ggg..",
      ".gg..g....g..gg.",
      "...kk......kk...",
      "....KKKKKKKK....",
      "...KKKKKKKKKK...",
      "..KKKMMWWMMKKK..",
      "..KKKMWBBWMKKK..",
      "..KKKMMWWMMKKK..",
      "...KKKKKKKKKK...",
      "....KKKRRKKK....",
      ".....kkkkkk....."
    ]
  },
  "droneB": {
    "w": 16,
    "pal": {
      "K": "#2b2438",
      "k": "#4a4160",
      "M": "#c8ccd8",
      "W": "#ffffff",
      "B": "#39a9ea",
      "R": "#ff4d4d",
      "g": "#7c8496"
    },
    "rows": [
      "..g.g......g.g..",
      ".ggggg....ggggg.",
      "...kk......kk...",
      "....KKKKKKKK....",
      "...KKKKKKKKKK...",
      "..KKKMMWWMMKKK..",
      "..KKKMWBBWMKKK..",
      "..KKKMMWWMMKKK..",
      "...KKKKKKKKKK...",
      "....KKKWWKKK....",
      ".....kkkkkk....."
    ]
  },
  "can": {
    "w": 11,
    "pal": {
      "M": "#d8dce8",
      "m": "#9aa2b4",
      "R": "#e2243a",
      "r": "#a8122a",
      "W": "#ffffff",
      "D": "#4a0d1b"
    },
    "rows": [
      "..DMMMMMD..",
      ".DMmMMMmMD.",
      ".DMMMMMMMD.",
      ".DrRRRRRrD.",
      ".DrRRRRRrD.",
      ".DrWWWWWrD.",
      ".DrWWWWWrD.",
      ".DrWWWWWrD.",
      ".DrRRRRRrD.",
      ".DrRRRRRrD.",
      ".DrRRRRRrD.",
      ".DmMMMMMmD.",
      "..DMMMMMD.."
    ]
  },
  "heart": {
    "w": 7,
    "pal": {
      "R": "#ff4d6d",
      "r": "#c41f47",
      "W": "#ffd0dc"
    },
    "rows": [
      ".RR.RR.",
      "RWRRRRR",
      "RWRRRRR",
      "rRRRRRr",
      ".rRRRr.",
      "..rRr..",
      "...r..."
    ]
  }
};
